### ISSUE TITLE
how to use 3DDFA_V2 detect pose?

### ISSUE THREAD

**Issue by ABC0408** [jixinya/EAMM#2]
Hello, 
I saw you provide the *npy file in test/pose/ folder, the shape is (1, 7).
I changed https://github.com/cleardusk/3DDFA_V2/blob/v0.12/demo.py#L91 default to "pose",  the result is like
https://github.com/cleardusk/3DDFA_V2/blob/v0.12/docs/images/trump_hillary_pose.jpg. 
No variables shape is (1, 7).

**Comment by jixinya** [comment]
Hi, I have uploaded the pose detection code based on 3DDFA_V2. Simply replace the corresponding file should get the final results.
